# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 125296a2506d1f992c958778daa52c864c5199500828a31ed40852475686aa94b89c5ebd7f03aef8e852e305b843e7dc11fc9962a4686f0ce6b145c3e3203e3f

test:
  secret_key_base: 3e3a9da90313bf41f28f44386431a23e0c2361e091941bbb34a55d531cec0cf78730be6dec5b502a99835a1c1e2b5229b832a1a53c878497c296bafd1626a8cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
